name: (( merge ))

networks: (( merge ))

jobs:
  - name: serf_z1
    template: serf
    instances: 2
    resource_pool: medium_z1
    networks:
      - name: cf1
        static_ips: (( merge ))
    properties:
      network_name: cf1
      serf:
        members: (( jobs.serf_z1.networks.cf1.static_ips ))
        role: gateway

  - name: warden_z1
    template:
      - warden
      - serf
    instances: 5
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      network_name: cf1
      serf:
        members: (( jobs.serf_z1.networks.cf1.static_ips ))
        role: warden

  - name: maestro_z1
    template:
      - maestro
      - serf
    instances: 2
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      network_name: cf1
      serf:
        members: (( jobs.serf_z1.networks.cf1.static_ips ))
        role: maestro
