name: (( merge ))

networks: (( merge ))

jobs:
  - name: warden_z1
    template: warden
    instances: 5
    resource_pool: medium_z1
    networks:
      - name: cf1
        static_ips: (( merge ))
    properties:
      network_name: cf1
      serf:
        members: (( jobs.warden_z1.networks.cf1.static_ips ))
        role: warden
